import pika
import sys

import json
from datetime import datetime

#Log and logs are generated by AI (sorry) so it is clearly visible in the terminal along all the different logs
def log(message, level="INFO"):
    """Print with prefix, timestamp, and level for better visibility in Docker logs"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[PYTHON-CONSUMER] [{timestamp}] [{level}] {message}", flush=True)

def main():
    log("=== South Park Messages Consumer Starting ===", "INFO")
    log("Initializing connection to RabbitMQ...", "INFO")

    try:
        credentials = pika.PlainCredentials("user", "password")
        params = pika.ConnectionParameters(
            host="rabbit-mq",          
            port=5672,
            virtual_host="/",         
            credentials=credentials,
            heartbeat=30,
            blocked_connection_timeout=30,
        )

        log("Connecting to RabbitMQ at rabbit-mq:5672...", "INFO")
        connection = pika.BlockingConnection(params)
        channel = connection.channel()

        log("Declaring queue 'southpark_messages'...", "INFO")
        channel.queue_declare(queue="southpark_messages", durable=True)

        def callback(ch, method, properties, body):
            try:
                message_data = json.loads(body.decode())
                author = message_data.get("author", "Unknown")
                message_body = message_data.get("body", "")
                log(f"📨 NEW MESSAGE from '{author}'", "MESSAGE")
                log(f"   Content: {message_body}", "MESSAGE")
                log("─" * 60, "MESSAGE")
            except json.JSONDecodeError:
                log(f"📨 Received (raw): {body.decode()}", "MESSAGE")
                log("─" * 60, "MESSAGE")

        channel.basic_consume(
            queue="southpark_messages",
            on_message_callback=callback,
            auto_ack=True,   
        )

        log("✓ Successfully connected to RabbitMQ", "SUCCESS")
        log("✓ Queue 'southpark_messages' ready", "SUCCESS")
        log("⏳ Waiting for messages...", "INFO")
        log("", "INFO")
        channel.start_consuming()

    except pika.exceptions.AMQPConnectionError as e:
        log(f"❌ Connection error: {e}", "ERROR")
        sys.exit(1)

    except KeyboardInterrupt:
        log("⚠️  Interrupted by user", "WARNING")
        if 'channel' in locals():
            channel.stop_consuming()
        if 'connection' in locals():
            connection.close()
        log("Consumer stopped gracefully", "INFO")
        sys.exit(0)

    except Exception as e:
        log(f"❌ Unexpected error: {e}", "ERROR")
        sys.exit(1)
